### ISSUE TITLE
Error on install -- provide manual install instructions if possible?

### ISSUE THREAD

**Issue by dcomtois** [frederich/quotefix#1]
I get this error when trying to install by executing OutlookQuoteFix.vsto, having to do with the key signature... Note: I don't have admin rights on this machine.

************** Texte de l'exception **************
System.Deployment.Application.InvalidDeploymentException: Exception lors de la lecture du manifeste à partir de file://(...)/Downloads/outlook_quotefix_1_0_0/OutlookQuoteFix.vsto : le manifeste n'est pas valide ou le fichier n'a pas pu être ouvert. ---> System.Deployment.Application.InvalidDeploymentException: La signature XML de manifeste n'est pas valide. ---> System.Security.Cryptography.CryptographicException: Impossible de créer SignatureDescription pour l'algorithme de signature fourni.
   à System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   à System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
   à System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
   à System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   à System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
   --- Fin de la trace de la pile d'exception interne ---
   à Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   à Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by frederich** [comment]
@dcomtois, thank you for reporting.

I need more information, to reproduce the bug. Which operating system do you use? Which office version, 32/64-bit?

**Comment by dcomtois** [comment]
This is on Windows 7, 64 bits

**Comment by frederich** [comment]
Not reproducible.

**Comment by AnotherAnonymousUser** [comment]
I have exactly the same problem. 

I use a Windows 7 Professional system, 64-bit, in a corporate environment. I have admin rights on the system.

The error message is exactly the same, albeit in another language.

I googled for _System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo_ because this caught my eye.

I found a few interesting sides, including:
- [(https://blogs.msdn.microsoft.com/smondal/2012/08/24/signaturedescription-could-not-be-created-for-the-signature-algorithm-supplied/)]
- [https://stackoverflow.com/questions/16573837/manifest-xml-signature-is-not-valid-on-client-machine-but-works-fine-on-develo?noredirect=1&lq=1]

On my system I have the following .NET runtimes installed:
- Microsoft .NET Framework 4.5
- Microsoft .NET Framework 4.5.1
- Microsoft .NET Framework 4.5.2
- Microsoft .NET Framework 4.6
- Microsoft .NET Framework 4.6.1

My gut feeling says that this problem needs to be solved on the developer side, by changing some settings in the development process, for example targeting a different .NET runtime.

But in order to make this work I am willing to install additional software on my side, too.

Please advise what I should try out. Thanks!

**Comment by frederich** [comment]
I'm not so lucky with the .Net solution. It's slow and blocks the UI thread.  I'll doing a rewrite in C++ in the next weeks, then the issue goes away.

**Comment by AnotherAnonymousUser** [comment]
If I can help you out with something like testing, just let me know.

**Comment by frederich** [comment]
@AnotherAnonymousUser, thanks. I'll contact you.

**Comment by raomin** [comment]
Same here.
![image](https://cloud.githubusercontent.com/assets/4460208/21842708/477b18d6-d7e8-11e6-9a82-506540d49f44.png)

I suppose you need to add in the release the certifcate you used for signing the component so it can be added to the truststore before installation.

**Comment by frederich** [comment]
@dcomtois, @AnotherAnonymousUser, @raomin, please test v1.0.1-beta, hopefully it will fix issue.

https://github.com/frederich/quotefix/releases/tag/v1.0.1-beta

**Comment by AnotherAnonymousUser** [comment]
Thank you for the beta release!

Just to make sure: how am I supposed to install the new plugin?

I tried to "execute" the _.vsto_ file, but I receive the following error. I think this is the same as the previous error:

![2017-01-17_16h46_24](https://cloud.githubusercontent.com/assets/25001984/22027716/ff40f88c-dcd4-11e6-94b3-cfd0fe89fad4.png)

**Comment by frederich** [comment]
@AnotherAnonymousUser next try. I've added the .pfx-file to the v1.01.-beta1 zip-archive. Please install the .pfx-file and then the .vsto-file.

**Comment by AnotherAnonymousUser** [comment]
I'm sorry for the late reply.

I installed the certificate by double-clicking the .pfx file. The import process went smoothly and the certificate was installed successfully.

Unfortunately, the same error message still appears:

> System.Deployment.Application.InvalidDeploymentException: Ausnahme beim Lesen des Manifests aus 'file:///C:/Users/.../Downloads/qf/OutlookQuotefix.vsto': Das Manifest ist möglicherweise ungültig, oder die Datei konnte nicht geöffnet werden. ---> System.Deployment.Application.InvalidDeploymentException: Die XML-Signatur des Manifests ist ungültig. ---> System.Security.Cryptography.CryptographicException: SignatureDescription konnte für den angegebenen Signaturalgorithmus nicht erstellt werden.

Do you have another idea?

**Comment by frederich** [comment]
@AnotherAnonymousUser, sorry I have no time to solve this strange issue. Please build quotefix from sources.
